pacifica/pacifica-metadata

- metadata/elastic/test/test_elastic.py
- metadata/orm/files.py
- requirements-dev.txt
- test_files/files.json
This should make the size field of a file a long for elasticsearch
matching the BigIntegerField peewee type.
#15
> fix #15 update size to be elasticsearch long

- metadata/rest/instrument_queries/instrument_user_search.py
- metadata/rest/test/test_instrumentinfo.py
Fixes #36
Changes the return for the instrumentinfo/by_user_id to provide an empty result set instead of a 404 when no instruments are found
#36
> Instrumentinfo query now returns empty set rather than 404

- metadata/rest/reporting_queries/summarize_by_date.py
Drops the time required for a file summary by date from 30s to 1-2s
#40
> Summaryinfo query churn fixes

- metadata/rest/instrument_queries/instrument_user_search.py
- metadata/rest/reporting_queries/summarize_by_date.py
- metadata/rest/test/test_instrumentinfo.py
- metadata/rest/user_queries/user_search.py
When searching for instruments and users by ID, the search engine massages the integer values to make them string-like so that you can search them as if they actually were strings. The function that carries this out is Postgres native, and requires a formatting term to carry out the process. The formatter that I picked was only good for numbers up to 999999, but the ID's used for the Dēmo instantiation were 7 digits, not 6. Expanded the formatted to handle numbers up to 99999999999.
#36
> Issue 36 instrumentinfo query fix

- metadata/rest/instrument_queries/query_base.py
- metadata/rest/test/test_userinfo.py
- metadata/rest/user_queries/query_base.py
This uses the appropriate instrument group relationship for determining
the category and the groups for the instrument.
N/A
> Remove the colon query mechanism for determining the instrument group

- .travis.yml
- metadata/elastic/orm.py
- metadata/elastic/test/__init__.py
- metadata/elastic/test/test_api.py
This adds sniffing to the Elasticsearch client library. This should hopefully help the client inspect the elasticsearch cluster and find a node that will allow uploads quicker.
N/A
> add Elasticsearch sniffing options to try retrying uploads

- metadata/orm/atool_proposal.py
- metadata/orm/citation_proposal.py
- metadata/orm/proposal_instrument.py
- metadata/orm/proposal_participant.py
- metadata/orm/utils.py
- metadata/rest/test/test_proposalinfo.py
- test_files/atool_proposal.json
- test_files/citation_proposal.json
- test_files/proposal_instrument.json
- test_files/proposal_participant.json
This adds a unicode proposal id to allow `index_hash` to be evaluated with a unicode string.
N/A
> one more unicode error

- metadata/rest/tkvinfo_queries/values_for_key.py
When a `get()` is done on a hash it will return `null` if the key doesn't exist.
N/A
> this is a quick fix seems doing a get() on a hash returns null

- .pre-commit-config.yaml
- metadata/elastic/test/test_elastic.py
- metadata/orm/analytical_tools.py
- metadata/orm/atool_proposal.py
- metadata/orm/citation_proposal.py
- metadata/orm/citations.py
- metadata/orm/contributors.py
- metadata/orm/files.py
- metadata/orm/groups.py
- metadata/orm/institutions.py
- metadata/orm/instruments.py
- metadata/orm/journals.py
- metadata/orm/keys.py
- metadata/orm/keywords.py
- metadata/orm/proposal_instrument.py
- metadata/orm/proposal_participant.py
- metadata/orm/proposals.py
- metadata/orm/transactions.py
- metadata/orm/users.py
- metadata/orm/values.py
This changes out all the string elasticsearch mappings (which default to 'text') to keywords so they can be aggregated in elastic search.
N/A
> switch out all the string mappings for keywords where appropriate

- docker-compose.yml
- docker-compose/Dockerfile.elastic
Changing docker-compose file to use the official ES 5.5.1 image from elasticsearch.co and to include the bits that allow cross-site requests to be made for testing
This changes the docker-compose.yml file to include options that are proper for ES 5.5, but are broken/changed from 2.4
Fixes #61
> Updating Elasticsearch docker configuration

- Dockerfile
- entrypoint.sh
This removes the docker python onbuild dependency for containers.
N/A
> remove docker python onbuild as its not recommended for production

- metadata/orm/atool_proposal.py
- metadata/orm/citation_proposal.py
- metadata/orm/proposal_instrument.py
- metadata/orm/proposal_participant.py
- metadata/orm/transactions.py
This reverts the change to make things keyword for elasticsearch types this should allow the addition of keywords to be added to existing elasticsearch mappings when they were type text.
N/A
> this fixes the elastic mapping to be text primary and have keywords also

- metadata/orm/user_group.py
This adds the hash of the two values as the ID as well as creating
the elastic mapping properly for the user_group table.
N/A
> Fix user group to be similar to other cross tables

- .pre-commit-config.yaml
- metadata/orm/base.py
- metadata/rest/orm.py
This roles back the default recursion depth to the default 0 and adds the recursion at 1 for elastic search uploading and updating
> reduce recursive queries on base checks

- metadata/rest/fileinfo_queries/files_with_tkv.py
- metadata/rest/reporting_queries/summarize_by_date.py
- metadata/rest/transaction_queries/query_base.py
- metadata/rest/user_queries/query_base.py
- metadata/rest/user_queries/user_search.py
- metadata/rest/userinfo.py
This removes the recursion depth for the rest methods that are used by status and reporting since they don't need that information.
N/A
> fix to_hash() methods to add default recursion depth

- metadata/orm/files.py
- metadata/orm/proposals.py
- metadata/orm/test/test_files.py
- metadata/orm/test/test_proposals.py
- metadata/orm/test/test_transactions.py
- metadata/orm/transactions.py
- test_files/files.json
- test_files/proposals.json
- test_files/transactions.json
This adds suspense date to the respective objects Proposal, Transactions and Files.
#106
> fix #106 add suspense date to objects

- metadata/admin_cmd.py
- metadata/test/test_admin.py
This adds the delete argument to render, it will allow admins to
really, really delete an entry in the database.
#119
> Fix #119 by adding a delete argument to render

- appveyor.yml
- metadata/rest/ingest.py
- metadata/rest/test/test_ingest.py
- test_files/cherrypy_catch.py
- travis/unit-tests.sh
Add CloudEvents hook in the metadata server so it will emit events when data is ingested.
#146
> Fix #146 Add event emittion to a notification service

- .gitignore
- .travis.yml
- metadata/orm/base.py
- metadata/orm/test/test_dbdates.py
This adds a suffix of `_0` and `_1` to the dates when doing a between
comparison for date attributes. This allows the curl from the REST API
to work instead of throwing errors.
Fix #151
> make the between operator act a bit different

- pacifica/metadata/orm/base.py
Revert the version attribute for all objects.
N/A Quick Fix
> Revert the version attribute for all objects

- pacifica/metadata/admin_cmd.py
- pacifica/metadata/rest/orm.py
- tests/core/admin_test.py
This adds more options to force delete from the API and from the
admin command line tools. New options will cascade delete the object
and related foreign keys in the database.
Fix #195
> Fix #157 add more expresive delete

- pacifica/metadata/orm/base.py
- pacifica/metadata/orm/institution_user.py
- pacifica/metadata/orm/instrument_data_source.py
- pacifica/metadata/orm/instrument_user.py
- pacifica/metadata/orm/project_instrument.py
- pacifica/metadata/orm/project_user.py
- pacifica/metadata/orm/transaction_user.py
This allows users to create relationships by name or UUID so they
don't have to look up the UUID for these cross reference objects.
N/A
> Add creating relationships by name and UUID

- .pre-commit-config.yaml
- pacifica/metadata/config.py
- pacifica/metadata/rest/doi_queries/doi_registration_entry.py
- pacifica/metadata/rest/doi_queries/doi_registration_update.py
- pacifica/metadata/rest/events.py
- pacifica/metadata/rest/ingest.py
- pacifica/metadata/rest/orm.py
This moves the event emit code to a central module so it can be
used elsewhere in the code.
> Move event emit code to common module.

- pacifica/metadata/rest/user_queries/query_base.py
Changing the user lookup query to use "user" in the where clause, not "person". We probably want to double-check the remainder of the rest queries to make sure that we didn't miss anybody else.
Fix #226
> Fix #226 UserInfo lookup fix

- pacifica/metadata/orm/base.py
- tests/rest/objectinfo_test.py
UUIDs should be serialized by just using str() on them.
Fix #225
> Fix #225 Add UUID check for json serialization

- pacifica/metadata/orm/base.py
- pacifica/metadata/rest/objectinfo.py
This adds parameters to the objectinfo hashlist function as part
of the rest interface. The parameters are passed as columns to hash
for the respective object.
Fix #236
> Fix #236 add columns options to hashlist

- .travis.yml
- appveyor.yml
- pacifica/metadata/orm/base.py
- pacifica/metadata/rest/fileinfo_queries/file_details.py
- pacifica/metadata/rest/ingest.py
- requirements.txt
This removes Python 2.7 support from Travis CI and Appveyor. This
also removes the six requirements as we are not supporting Python
2.7 anymore.
N/A
> Remove Python 2.7 support

- .travis.yml
- appveyor.yml
- tests/core/cmd_test.py
This adds Python 3.7 and 3.8 to Travis CI and Appveyor CI/CD
pipelines.
N/A
> Add Python 3.7 and 3.8 to Travis CI and Appveyor

- pacifica/metadata/rest/reporting_queries/transaction_reporting.py
Switching around the selection logic for the transaction summary query that is used for the Compliance Reporting tool
Fixes #274
> Fixing query logic for transaction summary reporting

- pacifica/metadata/rest/project_queries/project_lookup.py
Switching to use TransSIP instead of ProjectInstrument as it's more representative of reality in the metadata server
Query update to better correspond with project to instrument mappings in the newer schema
Fixes #277
> Changing the join table mapping on the instrument association lookup

- pacifica/metadata/orm/base.py
- tests/orm/base_test.py
- tests/orm/dbdates_test.py
Minor addition to orm/base.py to enable the system to filter out soft deleted entries (entries with a non-null deleted date). 
This just "makes sense" to me. The system shouldn't show anything that has been "deleted" unless you specifically ask it to do so (by adding a query param of "include_deleted"
Fixes #273
> Filtering out "soft deleted" entries.
