metadata/orm/base.py

Seems peewee raises and operational error if the database is already
connected
N/A

try except around the db connect

---

metadata/rest/fileinfo_queries/file_details.py

This adds in information regarding the stored hashtype and hashsum for file metadata retrieved from the database
#26

File hashsum and hashtype reporting

---

metadata/rest/fileinfo_queries/earliest_latest.py
metadata/rest/transaction_queries/query_base.py

Making the metadata engine a little smarter and more forgiving when it comes to object types that it will accept for summarization duties
#24

Object typing fix

---

metadata/rest/user_queries/user_search.py

Fixes 29
Fixes the user search view so that it properly sorts people's names now
29

Now sorting user search results by last/first name

---

metadata/orm/users.py
requirements-dev.txt

This makes sure all accessing to network_id in user object is
compared or set to a lower case version of the network_id
#31

fix #31 lower case all accesses and compares to network_id

---

metadata/orm/users.py

This deals with code that assumes pass by value vs pass by reference.

this needs to be set because everything is pass by reference

---

metadata/orm/base.py
metadata/orm/files.py
metadata/orm/instruments.py
metadata/orm/keys.py
metadata/orm/proposals.py
metadata/orm/users.py
metadata/orm/values.py

This creates needed indexes for accessing ranges of the objects by date.
#34

add indexes for updated created and deleted

---

metadata/rest/instrument_queries/instrument_user_search.py
metadata/rest/reporting_queries/summarize_by_date.py
metadata/rest/test/test_instrumentinfo.py

Trying to minimize data copying and shuffling around
#36

Issue 36 instrumentinfo query fix

---

metadata/rest/reporting_queries/summarize_by_date.py

Reverts pacifica/pacifica-metadata#38

Revert "Issue 36 instrumentinfo query fix"

---

.travis.yml
metadata/orm/__init__.py
metadata/orm/base.py
metadata/orm/test/base.py
metadata/orm/utils.py
metadata/rest/instrument_queries/instrument_term_search.py
metadata/rest/orm.py
metadata/rest/proposal_queries/proposal_term_search.py
metadata/rest/proposal_queries/proposal_user_search.py
metadata/rest/test/__init__.py
metadata/rest/transaction_queries/query_base.py
metadata/rest/transaction_queries/transaction_search.py
metadata/rest/user_queries/user_search.py
requirements-dev.txt
travis/before-install.sh
travis/test-script.sh
travis/unit-tests.sh

This should remove docker as a dependency for travis builds.
N/A

this fixes travis so it should work

---

setup.py

Add requirements.txt parsing to the setup.py script
N/A

add the requirements parsing to the setup.py

---

metadata/rest/tkvinfo_queries/values_for_key.py

This returns a dictionary with the values being the key and the transactions being a list instead of single transactions.
N/A

make tkvinfo return lists instead of single values

---

metadata/rest/test/test_tkvinfo.py
metadata/rest/tkvinfo_queries/values_for_key.py
test_files/transactions.json

This adds a date range options to the values for key based on transaction create time.
N/A

add datetime range to values for key

---

metadata/elastic/orm.py

This should add a 60 second timeout which mirrors the sniffer timeout.
N/A

Quickfix for increasing timeouts to the same as sniffer timeouts

---

metadata/orm/analytical_tools.py
metadata/orm/citations.py
metadata/orm/contributors.py
metadata/orm/files.py
metadata/orm/groups.py
metadata/orm/institutions.py
metadata/orm/instruments.py
metadata/orm/journals.py
metadata/orm/keys.py
metadata/orm/keywords.py
metadata/orm/proposals.py
metadata/orm/users.py
metadata/orm/values.py

This adds in field alternate types for text values that we want to be aggregate-able (is that a word??)
Fixes #60

Issue 60 new fieldtypes

---

entrypoint.sh

Add database create script to entrypoint so docker container has initial state
N/A

Add database create script to entrypoint.sh

---

metadata/elastic/orm.py
metadata/elastic/test/test_elastic.py
metadata/orm/base.py
metadata/orm/instruments.py
metadata/rest/elasticupdate.py
metadata/rest/root.py
metadata/rest/test/test_elasticupdate.py

This is adding support to allow the ElasticSearch index to be updated with new information (specifically, recursively nested foreign key data) after new info is available in the relational db
Should clear #73

Issue 73 nested mapping

---

GenMetadataModelMD.py
METADATA_MODEL.md

This commit adds an "Attributes" column to the table that lists SQL attributes, including: nullability, primary key, and sequence.
Closes #77

Add "Attributes" column to table.

---

metadata/elastic/elasticupdate.py

This properly yields actions to elasticsearch bulk upload so it can stream through the data without much memory usage
EOM errors

make this more streaming

---

metadata/rest/reporting_queries/detailed_transactions_list.py
metadata/rest/reporting_queries/summarize_by_date.py

Clears up confusion with date-based searching for status information
#90

Provide a clearer interface for date-based searching

---

metadata/rest/orm.py

This should be removed so it won't produce a huge list.
N/A

quickfix add trans_links to exclude list

---

MetadataServer.py
metadata/__init__.py
setup.py
travis/unit-tests.sh

Adds the entry point in setup.py for other scripts to use.
N/A

setup entry point for console scripts

---

MetadataServer.py
appveyor.yml
metadata/__init__.py
metadata/rest/test/test_tkvinfo.py
travis/unit-tests.sh

Add windows appveyor testing
N/A

try adding appveyor.yml file

---

README.md

This adds the badge to the README
N/A

add appveyor to readme

---

METADATA_MODEL.md
metadata/orm/proposals.py
metadata/orm/test/test_proposals.py

This adds short name attribute to proposal
#95

fix #95 add proposal short name

---

DatabaseCreate.py
GenMetadataModelMD.py
metadata/orm/test/test_utils.py
metadata/orm/utils.py
requirements-dev.txt

uses newer version of pylint
N/A

use new version of pylint

---

docker-compose/Dockerfile.elastic
metadata/elastic/__init__.py
metadata/elastic/test/test_api.py
metadata/orm/__init__.py
metadata/orm/atool_proposal.py
metadata/orm/atool_transaction.py
metadata/orm/base.py
metadata/orm/citation_contributor.py
metadata/orm/citation_keyword.py
metadata/orm/citation_proposal.py
metadata/orm/citations.py
metadata/orm/contributors.py
metadata/orm/file_key_value.py
metadata/orm/files.py
metadata/orm/institution_person.py
metadata/orm/instrument_custodian.py
metadata/orm/instrument_group.py
metadata/orm/proposal_instrument.py
metadata/orm/proposal_participant.py
metadata/orm/test/base.py
metadata/orm/test/test_dbdates.py
metadata/orm/trans_key_value.py
metadata/orm/transactions.py
metadata/orm/user_group.py
metadata/rest/fileinfo_queries/files_with_tkv.py
metadata/rest/orm.py

Doing away with extraneous calls to the database to look up information that we already had from the primary lookup table
#101

Issue 101 query optimization testing

---

requirements-dev.txt
requirements.txt

add requirements fix

---

METADATA_MODEL.md
metadata/orm/__init__.py
metadata/orm/doidatasets.py
metadata/orm/doiresource.py
metadata/orm/test/test_doidatasets.py
metadata/orm/test/test_doiresource.py
test_files/doidatasets.json
test_files/doiresource.json
test_files/loadit.py

Add DOI Data Set and DOI Resource models.
fix #107

add initial doi model for data sets and resources

---

metadata/rest/proposal_queries/proposal_has_data.py

fix #124 this swaps start and end dates.
fix #124

reverse start and end dates

---

metadata/admin_cmd.py
metadata/test/test_admin.py

This also removes the document from elasticsearch as well
Fix #119

Close #119 quick fix forgot to remove from ES

---

metadata/rest/transaction_queries/query_base.py

updated transactioninfo query for release_state

---

metadata/rest/objectinfo.py

This passes the kwargs from get objectinfo as a where args to subset the count.
N/A

pass the where args from objectinfo to select a subset for count

---

appveyor.yml
requirements-dev.txt

add pylint lock to requirements
#143

fix #143 add pylint lock to <2.0

---

pacifica/metadata/orm/__init__.py
pacifica/metadata/orm/proposal_group.py
setup.py
tests/orm/proposal_group_test.py
tests/test_files/loadit_test.py
tests/test_files/proposal_group.json

This adds the proposal group mapping object.
fix #160

fix #160 - Add proposal group orm object

---

.travis.yml
appveyor.yml
docker-compose.yml
pacifica/metadata/admin_cmd.py
pacifica/metadata/orm/sync.py
tests/core/admin_test.py
tests/core/cmd_test.py

This adds a database management subcommands for creating/updating
the database. This also has a subcommand for checking the version
returning 0/-1 for success and failure respectively.
N/A

Add database management command

---

.travis.yml
METADATA_MODEL.md
README.md
appveyor.yml
pacifica/metadata/admin_cmd.py
pacifica/metadata/config.py
pacifica/metadata/orm/all_objects.py
pacifica/metadata/orm/sync.py
pacifica/metadata/orm/transactions.py
pacifica/metadata/orm/transsap.py
pacifica/metadata/orm/transsip.py
pacifica/metadata/rest/fileinfo_queries/earliest_latest.py
pacifica/metadata/rest/ingest.py
pacifica/metadata/rest/proposal_queries/proposal_has_data.py
pacifica/metadata/rest/reporting_queries/detailed_transactions_list.py
pacifica/metadata/rest/reporting_queries/summarize_by_date.py
pacifica/metadata/rest/tkvinfo_queries/values_for_key.py
pacifica/metadata/rest/transaction_queries/query_base.py
pacifica/metadata/rest/transaction_queries/transaction_last.py
pacifica/metadata/rest/transaction_queries/transaction_search.py
pacifica/metadata/rest/transaction_queries/transactions_multi_search.py
tests/orm/transaction_release_test.py
tests/orm/transactions_test.py
tests/orm/transsap_test.py
tests/orm/transsip_test.py
tests/test_files/loadit_test.py
tests/test_files/transactions.json
tests/test_files/transsap.json
tests/test_files/transsip.json

This creates an analytical transaction and makes transactions a
first class orm object by moving connections to users, projects
and instruments to a different new object, TransSIP.
The analytical transaction will be a new object `TransSAP` linking
transactions, analytical tools and projects.
fix #172 
fix #165

add analytical transaction

---

pacifica/metadata/rest/doi_queries/doi_modified_time_update.py
pacifica/metadata/rest/doi_queries/doi_registration_base.py
pacifica/metadata/rest/doi_queries/doi_registration_entry.py
pacifica/metadata/rest/doiupload.py
pacifica/metadata/rest/transaction_queries/transaction_release_state.py
tests/rest/doiupload_test.py

Adding some more logic for dealing with the OSTI update process better and more efficiently
Adding in more logic to better streamline the DOI updates return channel interactions with OSTI
#173

More DOI Logic Tweaks

---

entrypoint.sh
pacifica/metadata/admin_cmd.py

Now using new table create logic
Fixes #175

Tweaking entrypoint script

---

pacifica/metadata/orm/sync.py

This needs to be force inserted
N/A

We need to force insert when looping over transactions

---

README.md

Copied the badge urls from another project and didn't fix them...
N/A

didn't get the right badge urls

---

LICENSE

Fix license should be LGPL

---

appveyor.yml
pacifica/metadata/rest/transaction_queries/query_base.py

Issues when database would return None type for file sizes and get_release_states would barf
#182

Fix for edge case error for transactions with no files

---

pacifica/metadata/rest/transaction_queries/query_base.py

Ok. This time for sure!

---

docs/configuration.md
pacifica/metadata/config.py
pacifica/metadata/rest/ingest.py

This adds a configuration option to disable notifications.
Fix #181

Add disable notifications config option

---

README.md

This fixes metadata model links in README.md
Fix #187

Fix Metadata Model Links

---

pacifica/metadata/rest/doi_queries/doi_registration_update.py

Problem was real data having extra keys that were not in the list of allowed keys
Fixes #190

Extra key problems

---

.travis.yml
docker-compose.yml

This adds a travis stage to add docker container testing using
docker-compose.
N/A

Add docker image testing

---

pacifica/metadata/rest/fileinfo_queries/file_details.py
tests/test_files/files.json

This adds unicode filename and subdir to the test data set so we can
verify the rest interfaces are compatible with unicode characters.
Fix #154

Fix #154 unicode filename and subdir issues

---

.travis.yml
pacifica/metadata/orm/sync.py
pacifica/metadata/orm/sync_updates/update_2_0_to_2_1.py

This verifies that the schema upgrade and creating a new schema
both turn out the same schema... hopefully.
N/A

Add pgsql differ travis step

---

pacifica/metadata/orm/relationships.py
requirements-dev.txt
requirements.txt

Fix Spelling Error

---

setup.py

Fix project url

---

.travis.yml
appveyor.yml

This installs elasticsearch less than 7 to make the pipeline work.
N/A

Install older elasticsearch to make pipeline work

---

pacifica/metadata/rest/transaction_queries/transaction_search.py

Adding a little better support for paging functionality in the transaction retrieval and display logic
#208

Adding in minor changes to better paginate status item responses

---

.travis.yml
pacifica/metadata/orm/groups.py
pacifica/metadata/orm/instrument_key_value.py
pacifica/metadata/orm/keys.py
pacifica/metadata/orm/relationships.py
pacifica/metadata/orm/sync.py
pacifica/metadata/orm/sync_updates/update_2_1_to_3_0.py
pacifica/metadata/orm/sync_updates/update_3_0_to_4_0.py
pacifica/metadata/orm/values.py
requirements.txt
tests/orm/base_test.py
tests/orm/groups_test.py
tests/orm/instrument_key_value_test.py
tests/orm/keys_test.py
tests/orm/values_test.py
tests/rest/fileinfo_test.py
tests/test_files/groups.json
tests/test_files/instrument_key_value.json
tests/test_files/keys.json
tests/test_files/values.json

This adds columns display_name and description to Keys, Values
and Groups. The Instrument Key Value mapping should also get a
Relationships mapping to determine use if different key values
with respect to instruments.
Fix #215 
Fix #216

Fix #216 and Fix #215 Add Columns

---

pacifica/metadata/orm/instrument_key_value.py

Trying to get instrument key value relationships to add by name.
N/A

Add relationships by name for instrument key value

---

pacifica/metadata/orm/base.py
pacifica/metadata/rest/objectinfo.py
tests/rest/objectinfo_test.py

This changes some objectinfo parameters to add introspection to
determine the field types.
N/A

Add introspection

---

.pre-commit-config.yaml
CHANGELOG.md

Add ChangeLog

---

pacifica/metadata/rest/root.py
tests/rest/orm_test.py

Add nice URL to status metadata services.
Fix #223

Fix #223 add nice url

---

CHANGELOG.md

Add Changelog v0.10.2

---

pacifica/metadata/rest/transaction_queries/transaction_release_state.py

Removing unnecessary criteria from get_release_states functionality

---

CHANGELOG.md

Add Changelog v0.10.3

---

CHANGELOG.md

Add Changelog for v0.11.0

---

pacifica/metadata/rest/user_queries/query_base.py

This renames more of the person_id references to user_id or adds
both just in case.
Fix #238

Quick Fix #238 Missed a column rename

---

CHANGELOG.md

Add Changelog v0.11.1

---

requirements.txt

Try removing lock on psycopg2

---

CHANGELOG.md

Version v0.12.0

---

pacifica/metadata/orm/relationships.py
pacifica/metadata/orm/sync.py
pacifica/metadata/orm/sync_updates/update_2_1_to_3_0.py
pacifica/metadata/orm/sync_updates/update_3_0_to_4_0.py
pacifica/metadata/orm/sync_updates/update_4_0_to_5_0.py
pacifica/metadata/orm/sync_updates/update_5_0_to_6_0.py
pacifica/metadata/orm/sync_updates/update_6_0_to_7_0.py

This should have been fixed in #249 but wasn't so I'm trying again.
This fixes several issues:
* Rename principle to principal but doing it with peewee so it sticks
* Update comments on update modules so they reflect versions
* Refactor update methods so they are dynamic in OrmSync class
Fix #251

Fix #251 Rename Relationships Try 2

---

.travis.yml
appveyor.yml
pacifica/metadata/admin_cmd.py
pacifica/metadata/orm/sync_updates/update_6_0_to_7_0.py
requirements-dev.txt
setup.py
tests/__init__.py
tests/core/admin_test.py
tests/core/cmd_test.py
tests/orm/base_test.py
tests/orm/connect_test.py
tests/rest/__init__.py
tests/rest/doiupload_test.py
tests/rest/ingest_test.py
tests/rest/tkvinfo_test.py

This moves all the testing done in the appveyor and travis scripts into
PyTest scripts that are run in code.
N/A

This simplifies the testing to PyTest

---

CHANGELOG.md

Adds changelog for version 0.12.1
N/A

Add Changelog for version 0.12.1

---

CHANGELOG.md

Add Changelog entry for v0.12.2
N/A

Add Changelog v0.12.2

---

pacifica/metadata/orm/base.py

this appears to fix the hashing and ordering issues

---

CHANGELOG.md
appveyor.yml
tests/core/cmd_test.py

Add Changelog v0.12.3
Fix #263

Add Changelog v0.12.3

---

CHANGELOG.md

Add Changelog for v0.12.4

---

pacifica/metadata/rest/reporting_queries/transaction_reporting.py
pacifica/metadata/rest/transactioninfo.py
tests/rest/transactioninfo_test.py

Adding in functionality for more streamlined transaction summary info for compliance reporting
#270

Compliance query testing

---

.pre-commit-config.yaml
.travis.yml
Dockerfile
appveyor.yml
docs/GenMetadataModelMD.py
pacifica/metadata/orm/sync_updates/update_6_0_to_7_0.py
requirements-dev.txt
requirements.txt
setup.py
tests/core/cmd_test.py
tests/rest/orm_test.py

This moves requirements into setup.py and removes references to the
file from the pipelines.
N/A

Fix Requirements

---

CHANGELOG.md

- Pull #271 and #275 Add Transaction Reporting API by [@kauberry](https://github.com/kauberry)
- Pull #278 Project Lookup Refinement by [@dmlb2000](https://github.com/dmlb2000)
- Pull #281 Update Packaging (pip>=20) by [@dmlb2000](https://github.com/dmlb2000)
- Pull #280 Default Filter Soft Deletes by [@kauberry](https://github.com/kauberry)
N/A

v0.13.0: Happy Mother's Day!
